### ISSUE TITLE
color prop - not changing the color value of the component

### ISSUE THREAD

**Issue by josephinebienes** [hello-pangea/color-picker#7]
The color doesn't seem to change in the component when another component is used to set the color value.

Eg,

```
const [colorValue, setColorValue] = useState<string>()
...
...

<ChromePicker color={colorValue} />
<CirclePicker onChange={(e) => setColorValue(e.hex)}
```

If I use the `CirclePicker` component to set the color value, the `ChromePicker` doesn't pick up that color change.

![image](https://user-images.githubusercontent.com/64127913/191213005-988aa5b3-6519-4d5d-b391-1d960ad78965.png)

**Comment by Xhale1** [comment]
Thanks for the catch! The `color` props was implemented more like a default color. This is fixed in 1ad3c077b9451498f595bc79cb6c57cfc1abf1a5, included in version 3.2.0.

I also added a `defaultColor` prop for those who need that functionality as well as a new story which demonstrates using the `color` prop.
